from pathlib import Path


FILES = {
    "README.md": "# {name}\n\nGenerated by PromptForge.\n",
    "SKILL.md": "# Skill\n\nDescribe the skill here.\n",
    "prompt.md": "# Prompt\n\nWrite the core prompt here.\n",
    "examples.md": "# Examples\n\nAdd examples here.\n",
    "eval.md": "# Evaluation\n\nDescribe evaluation criteria.\n",
    "metadata.yaml": (
        "name: {name}\n"
        "version: 0.1.0\n"
        "author:\n"
        "description:\n"
    ),
    "CHANGELOG.md": "# Changelog\n\n## 0.1.0\n- Initial scaffold\n",
}


def create_skill(name: str) -> None:
    root = Path("skills") / name

    if root.exists():
        raise FileExistsError(f"Skill '{name}' already exists.")

    root.mkdir(parents=True)

    for filename, template in FILES.items():
        (root / filename).write_text(
            template.format(name=name),
            encoding="utf-8",
        )

    print(f"✓ Created skill: {root}")